#!/bin/bash

# run stage 1
fldr="stage1"
stage=1

for ((cong=$CONG_MIN; cong<=$CONG_MAX; cong++))
do
for ((chain=1; chain<=$CHAINS; chain++))
do
	cong_str=`printf %03d $cong`
        fileid=H$cong_str'_'$chain'_'$fldr
        echo $fileid
	Rscript 1_run_models.R $cong $chain $stage $BURN $ITER $THIN $fldr

done
	suffix=${BURN}_${ITER}_${THIN}
	Rscript 2_postprocess.R $cong $stage $fldr $suffix
done
